import { Mongo } from 'meteor/mongo'
import { Meteor } from 'meteor/meteor'
import SimpleSchema from 'simpl-schema'
import shortid from 'shortid'

export const Links = new Mongo.Collection('links')

export const schema = new SimpleSchema({
  url: {
    type: String,
    label: 'Link',
    regEx: SimpleSchema.RegEx.Url,
  },
  name: {
    type: String,
    min: 1,
    label: 'Link Name',
  }})

const ValidationContext = schema.namedContext('linksContext')

export function getValidationContext() {
  return ValidationContext
}

if (Meteor.isServer) {
  Meteor.publish('links', function() {
    if(this.userId) {
      return Links.find({userId: this.userId})
    }
  })
}

Meteor.methods({
  'links.insert'(link) {
    if(!this.userId) {
      throw new Meteor.Error('not-authorized', 'User must be logged in')
    }
    ValidationContext.validate(link)
    Links.insert({
      _id: shortid.generate(), // A shorter id than is generated by Meteor
      userId: this.userId,
      url: link.url,
      name: link.name,
      visible: true,
    })
  },
  'links.setVisibility'(_id, visible) {
    if(!this.userId) {
      throw new Meteor.Error('not-authorized', 'User must be logged in')
    }
    new SimpleSchema({
      _id: { type: String, min: 1 },
      visible: {type: Boolean},
    }).validate({_id, visible})
    Links.update({ _id, userId: this.userId }, { $set: {visible} })
  },
})
